services:
  database:
    extends:
      file: docker-compose.yml
      service: database
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    network_mode: host
    volumes:
      - ./.mount/postgres-db:/var/lib/postgresql

